- id: '1653425353362'
  alias: Dryer complete announce
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.dryer
    from: Drying
    to: Idle
  condition: []
  action:
  - service: notify.alexa_media
    data:
      message: Dryer finished
      target: media_player.kitchen,media_player.living_room,media_player.bedroom
      data:
        type: tts
  mode: single
