esphome:
  name: esp32camtesta

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "84c8a5222915fd1cc5312e9751da285b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Camtesta Fallback Hotspot"
    password: "abidOehGp6ob"

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: flashlightaaa
    id: camera_flash

captive_portal:
    