esphome:
  name: freenove-cam-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "f54acefcb7f585f6ba7a610dea5ebf86"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Freenove-Cam-1 Fallback Hotspot"
    password: "LkpDs85DU8kV"

esp32_camera:
  name: My Camera Freenove 1
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO22
    scl: GPIO23
  reset_pin: GPIO15
  data_pins: [GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO25
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  resolution: 1600x1200
  vertical_flip: false
  horizontal_mirror: false

captive_portal:
    