esphome:
  name: sensor-node-1
  platform: ESP32
  board: esp-wrover-kit
  
# Bluetooth Tracker          
esp32_ble_tracker:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "86102db08495f808cc7ee4fd360b3946"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor-Node-1 Fallback Hotspot"
    password: "aiPfhMvWO7eq"
    
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
sensor:
  - platform: aht10
    temperature:
      name: "Living Room AHT10 Temperature"
    humidity:
      name: "Living Room AHT10 Humidity"
    update_interval: 60s



captive_portal:
