esphome:
  name: test-deepsleep1
  on_boot:
    then:
       script.execute: consider_deep_sleep

esp32:
  board: esp32dev
  
  framework:
    type: arduino
 
    

# Enable logging
logger:

# Enable Home Assistant API
api:
#xxx

ota:
  password: "6bd671fc63f69e2cbe636d4f3875065b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Deepsleep1 Fallback Hotspot"
    password: "ftxLnpthdz0T"
sensor:
  - platform: dht
    pin: GPIO13
    temperature:
      name: "Deep Sleep Test Room Temperature"
    humidity:
      name: "Deep Sleep Test Room Humidity"
    update_interval: 60s

# Deep Sleep

deep_sleep:
  id: deep_sleep_control
 # run_duration:  1min
  sleep_duration: 60min

    
binary_sensor:
  - platform: homeassistant
    id: prevent_deep_sleep
    entity_id: input_boolean.prevent_deep_sleep
   
    

switch:
- platform: gpio
  pin: GPIO2
  id: blue_led
  
- platform: template
  name: "Blue LED"
  optimistic: yes
  id: bluetemp
  turn_on_action:
  - switch.turn_on: blue_led
  turn_off_action:
  - switch.turn_off: blue_led
  
script:
  - id: consider_deep_sleep
    mode: queued
    then:
      - delay: 1min
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - logger.log: 'Skipping sleep, per prevent_deep_sleep'
          else:
            - deep_sleep.enter: deep_sleep_control
      - script.execute: consider_deep_sleep

captive_portal:


    